### ISSUE TITLE
Clicking cancel button jump to Initial ViewController on ios5.x simulator

### ISSUE THREAD

**Issue by zhoujie903** [alexanderjarvis/PXAlertView#10]
i write a Demo for this issue on :https://github.com/zhoujie903/PXAlertViewIssue.git
i modify some code in PXAlertView for running on ios5.x(xcode4.6.3)
I found a solution to this problem: 
in [- (void)dismiss:(id)sender] 
modify this line code [self.mainWindow makeKeyAndVisible] to [self.mainWindow makeKeyWindow]

**Comment by overminder** [comment]
I encountered the same problem on an iOS 8 iPhone 6 simulator (Xcode 6.3.1). The fix still works though.
