### ISSUE TITLE
Non expected behavior when showing an alert inside the completion block from an other alert

### ISSUE THREAD

**Issue by faesa** [alexanderjarvis/PXAlertView#20]
Thank you Alexander for making this great control available!

Problem:
The second alert seems to have a randomly behavior. Indeed, sometimes it's displayed, sometimes not.
And in all the cases, the bounce effect is not as smooth as the first alert.
Do you have any idea?

Thanks a lot.

**Comment by braveS** [comment]
Still have this issue.
Solved by putting the next PXAlertView into
 ```javascript
dispatch_after(dispatch_time(DISPATCH_TIME_NOW, NSEC_PER_SEC), dispatch_get_main_queue(), ^{ /* **here** */ });
```
