### ISSUE TITLE
Functionality for a next version of alert view

### ISSUE THREAD

**Issue by AJ1310** [alexanderjarvis/PXAlertView#30]
Hi, great work on this very useful class. Is it possible to add an option to disable or remove buttons in the alert view, to selectively dismiss in a non-canceling fashion until certain conditions have been met, that allow to proceed with its dismissal.

In case of finding it helpful, I can help with the coding of the said implementations.

**Comment by alexanderjarvis** [comment]
Unclear and unwanted, so closing.
