### ISSUE TITLE
does not support landscape orientation?

### ISSUE THREAD

**Issue by torinnguyen** [alexanderjarvis/PXAlertView#55]
Please see screenshot here
http://take.ms/b8k35Q

**Comment by alexanderjarvis** [comment]
Are you using the latest from the git repo?

**Comment by torinnguyen** [comment]
I'm using pod as instructed.
pod 'PXAlertView', '~> 0.1.0'

**Comment by alexanderjarvis** [comment]
Try this and let me know if there is any difference. Perhaps a new version needs to be released to cocoapods.

pod ‘PXAlertView', :git => 'https://github.com/alexanderjarvis/PXAlertView.git'



On 23 June 2015 at 11:28:17, Torin Nguyen (notifications@github.com) wrote:

I'm using pod as instructed.
pod 'PXAlertView', '~> 0.1.0'

**Comment by TuWei1992** [comment]
i use ``` pod 'PXAlertView', :git => 'https://github.com/alexanderjarvis/PXAlertView.git' ``` but the same problem still exists.
My App supports the horizontal screen, but I set up the ViewController does not support, when the pop-up Alert when the mobile phone will appear this problem
