### ISSUE TITLE
minor bug

### ISSUE THREAD

**Issue by kissferenc** [alexanderjarvis/PXAlertView#57]
https://github.com/alexanderjarvis/PXAlertView/blob/master/Classes/PXAlertView.m#L432

I'm found a little bug on the link above.
This is the right code:

	NSUInteger index = [self.buttons indexOfObject:sender];
	if (index != NSNotFound) {
		buttonIndex = index;
	}

**Comment by alexanderjarvis** [comment]
Thanks!
